### ISSUE TITLE
RegisterExtensionType >> function call doesn't match any overload

### ISSUE THREAD

**Issue by edwingeng** [xanathar/moonsharp#100]
The first **lua.DoString** in the following code will result in: function call doesn't match any overload, while the second one won't.

~~~C#
public class Foo
{
    public static void Log1(string msg) { }
}

public static class FooExtension
{
    public static void Log2(this Foo self, string msg) { }
}
~~~

~~~C#
UserData.RegisterType<Foo>();
UserData.RegisterType<Dictionary<int, int>>();
UserData.RegisterExtensionType(typeof(FooExtension));

var lua = new Script();
lua.Globals["DictionaryIntInt"] = typeof(Dictionary<int, int>);

var script = @"local dict = DictionaryIntInt.__new(); local v; dict.TryGetValue(0, v)";
lua.DoString(script);
lua.DoString(script);
~~~

No exception will be thrown if **UserData.RegisterExtensionType** is removed.

Unity 5.1.1

**Comment by xanathar** [comment]
Suuuper odd.

I'll check immediately!

**Comment by xanathar** [comment]
Ok bug found - it's in the management of out parameters of value type (e.g. out int).
The extension method thingie is just a red-herring - it exposes the bug but has no real role in this bug . Fix coming very very soon - at this point I'm targetting a thursday release with cumulative fixes.

**Comment by edwingeng** [comment]
Thank you for your quick response :)

**Comment by xanathar** [comment]
I fixed this on the master branch.. I'll do a release asap.

Just a note: out parameters are ignored by moonsharp in the call and passed as return values.. so:

```
success, value = dict.TryGetValue(key) 
```
