### ISSUE TITLE
file.* and os.* unimplemented in lua standard library http://www.moonsharp.org/MoonSharpStdLib.pdf

### ISSUE THREAD

**Issue by zaxebo1** [xanathar/moonsharp#104]
as per http://www.moonsharp.org/MoonSharpStdLib.pdf
file.* , os.* are still unimplemented, without them it is very difficult to have a real world lua script up and running. 
Will these functions be implemented in future, or they will never be implemented by Moon#- and are intended to be implemented always by hosting app (As per PDF).

**Comment by xanathar** [comment]
file, io and os are implemented.. I just updated the pdf.

**Comment by zaxebo1** [comment]
Thanks
