### ISSUE TITLE
Capturing varargs in table from inner scope causes null ref exception

### ISSUE THREAD

**Issue by jacobdufault** [xanathar/moonsharp#110]
```lua
function Obj(...)
    do
        local args = { ... }
    end
end
Obj(1)
```

Stack trace:
```
NullReferenceException: Object reference not set to an instance of an object
MoonSharp.Interpreter.Execution.VM.Processor.Processing_Loop (Int32 instructionPtr) (at moonsharp/src/MoonSharp.Interpreter/Execution/VM/Processor/Processor_InstructionLoop.cs:186)
MoonSharp.Interpreter.Execution.VM.Processor.Call (MoonSharp.Interpreter.DynValue function, MoonSharp.Interpreter.DynValue[] args) (at moonsharp/src/MoonSharp.Interpreter/Execution/VM/Processor/Processor.cs:70)
MoonSharp.Interpreter.Script.Call (MoonSharp.Interpreter.DynValue function, MoonSharp.Interpreter.DynValue[] args) (at moonsharp/src/MoonSharp.Interpreter/Script.cs:472)
MoonSharp.Interpreter.Script.Call (MoonSharp.Interpreter.DynValue function) (at moonsharp/src/MoonSharp.Interpreter/Script.cs:431)
MoonSharp.Interpreter.Script.DoString (System.String code, MoonSharp.Interpreter.Table globalContext) (at moonsharp/src/MoonSharp.Interpreter/Script.cs:336)
```

**Comment by xanathar** [comment]
Thanks for the report. I'm on holiday now, will check out after Sep 10th.

----- Messaggio originale -----
Da: "Jacob Dufault" <notifications@github.com>
Inviato: ‎31/‎08/‎2015 01:38
A: "xanathar/moonsharp" <moonsharp@noreply.github.com>
Oggetto: [moonsharp] Capturing varargs in table from inner scope causes nullref exception (#110)

function Obj(...)
    do
        local args = { ... }
    end
end
Obj(1)Stack trace:
NullReferenceException: Object reference not set to an instance of an object
MoonSharp.Interpreter.Execution.VM.Processor.Processing_Loop (Int32 instructionPtr) (at moonsharp/src/MoonSharp.Interpreter/Execution/VM/Processor/Processor_InstructionLoop.cs:186)
MoonSharp.Interpreter.Execution.VM.Processor.Call (MoonSharp.Interpreter.DynValue function, MoonSharp.Interpreter.DynValue[] args) (at moonsharp/src/MoonSharp.Interpreter/Execution/VM/Processor/Processor.cs:70)
MoonSharp.Interpreter.Script.Call (MoonSharp.Interpreter.DynValue function, MoonSharp.Interpreter.DynValue[] args) (at moonsharp/src/MoonSharp.Interpreter/Script.cs:472)
MoonSharp.Interpreter.Script.Call (MoonSharp.Interpreter.DynValue function) (at moonsharp/src/MoonSharp.Interpreter/Script.cs:431)
MoonSharp.Interpreter.Script.DoString (System.String code, MoonSharp.Interpreter.Table globalContext) (at moonsharp/src/MoonSharp.Interpreter/Script.cs:336)

**Comment by jacobdufault** [comment]
Sure, have a good vacation.

**Comment by xanathar** [comment]
Fixed on master, will release asap.
