### ISSUE TITLE
Calling .remove(func) on a C# static event after a .add(func) makes further .add()'s fail to be called

### ISSUE THREAD

**Issue by TheMightyGit** [xanathar/moonsharp#112]
These steps happen in my code (using 0.9.8)...

* I have a C# **static** event, and in Lua code I **myEvent.add(lua_func)** to it. Event triggers lua code just fine. Hooray!
* I use **myEvent.remove(lua_func)** to remove it from the event. Event no longer triggers lua code, as expected.
* I use **myEvent.add(another_lua_func)** on event. But this code is not called when the event triggers :(

If I put in a dummy delegate before the above - it all works as expected.

So I *think* that when I remove the last delegate from the event it somehow resets its state, and for some reason from then on Moonsharp is no longer looking at the same event? As if returning the event it to null actually created a new event object (I'm no C# expert, but it seems that events/delegate do some magic in their null state).

Does this sound plausible?

NOTE: I have previously noticed that I need to Unregister and Register classes with static events in them if I null any of the static events, otherwise they no longer work - this seems like its the same(?) issue.

**Comment by TheMightyGit** [comment]
Using net35 in Unity, I should add.

**Comment by xanathar** [comment]
Event management in MoonSharp is enormously complex, so a bug there is not unlikely !

Will check this asap.

**Comment by TheMightyGit** [comment]
Cool :) For now I can use my work around. Good luck bug hunting. Let me know if you have any trouble reproducing it, if you do then I can try and make a minimal Unity project that exhibits the problem.

**Comment by xanathar** [comment]
Solved on master (not yet deployed on binaries!)

**Comment by TheMightyGit** [comment]
Confirmed working using latest src in Unity project. \o/ Thank you :D

**Comment by xanathar** [comment]
You're welcome :)
