### ISSUE TITLE
Debugger floods with "Execution finished"

### ISSUE THREAD

**Issue by GAMELASTER** [xanathar/moonsharp#113]
Hello,

I have LUA, and some functions what is Called so much, and when i use debugger, the console is spammed with "Execution finished", the Flash lags and game using so much RAM. How to disable that messages?

Thanks

**Comment by xanathar** [comment]
Sorry for the late answer. Probably the best way would be to allow disabling temporarily the script. I'll add this to the features desiderata for next versions.

**Comment by xanathar** [comment]
Solved.
Added a "DebuggerEnabled" property so that execution of the debugger subsystem can be disabled for some script invocations.

Will be released asap to master branch.
