### ISSUE TITLE
MoonSharpVisible on class

### ISSUE THREAD

**Issue by DanielAdolfsson** [xanathar/moonsharp#122]
It's not uncommon to extend classes that you don't have source access to, and not being able to hide parent members could really become a problem.

I propose allowing MoonSharpVisible (or if you want to create another annotation for that) to set the default access level for all members of that class. This would allow us to only expose the members we want, no matter how deep in the inheritance tree we are.

**Comment by xanathar** [comment]
Good suggestion!

**Comment by xanathar** [comment]
Done with several new features impacting this. Will be available very very asap on git and soon as a release.

**Comment by DanielAdolfsson** [comment]
It's not exactly what I suggested, but it's a real upgrade!

To clarify what I meant:
Suppose we have a large Base class that has maybe 20 different public methods, and 5 different public properties. If you don't want to expose any of them, you have to use [MoonSharpHideMember()] for each method and property.

Another solution would obviously to use the new Proxy object, but that won't work if the class you're extending have protected members; then you'd have to extend the base class anyway.

What I suggested was something along the line of [MoonSharpIgnorePublic] or similar that would ignore the public members unless they have been explicitly been made visible using [MoonSharpVisible].

My current problem, however, can be solved with a Proxy object.

Thanks for a great scripting engine by the way!

**Comment by xanathar** [comment]
Just a quick note... sadly I noticed after the commit that the proxy
objects as they were implemented don't work very well with inheritance.

I've already fixed them and a commit is coming.. so, sorry, but next commit
will break your build :)

On Sat, Jan 23, 2016 at 12:05 PM, Daniel Adolfsson <notifications@github.com

**Comment by DanielAdolfsson** [comment]
How do you mean? 

It looks, to me at least, as if the proxy is mapped directly to type. I don't think it should care about inheritance at all.

class Base {}
class SubClass : Base {}

If you, however, do want to make a proxy that has been registered for <Base> to be used for SubClass objects as well; then you would need some kind of logic that allows us to register a proxy for SubClass as well and prioritize that proxy when making the conversion.

No worries, I'll wait until you have committed your stuff :)

**Comment by xanathar** [comment]
The problem with inheritance is that now proxies work only with exactly the
type they are proxying.

So for example, let's say your proxy wraps "Transform" in Unity.. you
probably want to be able to pass your proxy to a function accepting a
variable of type "Component" but with the latest commit this is not
possible through proxies.

Will commit soon :)
I just have to do a little planning work for the upcoming global game jam
in my town and I'm back on moonsharp :D


On Sat, Jan 23, 2016 at 12:48 PM, Daniel Adolfsson <notifications@github.com
