### ISSUE TITLE
Arrays misses the first row.

### ISSUE THREAD

**Issue by OlofHaglund** [xanathar/moonsharp#123]
When an array is returned the first row is missing. 
Following code:
```
function Test()
	array = {}
	array[0] = 0
	array[1] = 1
	array[2] = 2
	return array
end
```
In C# the result is
```
DynValue.Table[0] is null
DynValue.Table[1] is 1
DynValue.Table[1] is 2
```

Bug found in net35 version.

**Comment by OlofHaglund** [comment]
Found out that it should be like that.

**Comment by xanathar** [comment]
Sorry if I missed this, but thanks for the report anyway.. and thanks for closing it :)
