### ISSUE TITLE
Exceptions and unexpected behavior when storing multiple return values in the "same" variable.

### ISSUE THREAD

**Issue by 7BiTpsycho** [xanathar/moonsharp#124]
Howdy!
Before we get started: I know that the following code is considered as bad practice. Regardless, the code throws exceptions during parse time which should not occur(in fact the code is perfectly valid and runs under Lua 5.1, 5.2 and 5.3).
```lua
t = {"a", "b", "c", ["d"] = "f", ["e"] = 5, [65] = true, [true] = false}
function myFunc()
  return "one", "two"
end

print("Table Test 1:")
for k,v in pairs(t) do
  print(tostring(k) .. " / " .. tostring(v))
end
print("Table Test 2:")
for X,X in pairs(t) do
  print(tostring(X) .. " / " .. tostring(X))
end
print("Function Test 1:")
v1,v2 = myFunc()
print(v1)
print(v2)
print("Function Test 2:")
v,v = myFunc()
print(v)
print(v)
```
This produces the following output under Lua 5.1, 5.2 and 5.3:
```
Table Test 1:
1 / a
2 / b
3 / c
e / 5
65 / true
true / false
d / f
Table Test 2:
a / a
b / b
c / c
5 / 5
true / true
false / false
f / f
Function Test 1:
one
two
Function Test 2:
one
one
```
Running this script using MoonSharp 1.1.1.0 and 1.1.0.1 produces the following exception before any code is executed:
```
An unhandled exception of type 'System.ArgumentException' occurred in mscorlib.dll

Additional information: An item with the same key has already been added.
```
Commenting the following part out produces the following output:
```lua
--print(""Table Test 2:"")
--for X,X in pairs(t) do
--    print(tostring(X).. "" / ""..tostring(X))
--end
```
```
Table Test 1:
1 / a
2 / b
3 / c
e / 5
65 / true
true / false
d / f
Function Test 1:
one
two
Function Test 2:
two
two
```
MoonSharp seems to use the second return value, while Lua uses the first. Also Lua handles the usage of variables with the same name for for-iterations correctly. This is no big issue as you shouldn't really do either of those things, but it is a bug regardless.
The MoonSharp tests were done in C# using a Console Application with version 4.6.1 of the .NET framework.
```c#
using System;
using MoonSharp.Interpreter;

internal class Program
{
    private static void Main(string[] args)
    {
        Script.DefaultOptions.DebugPrint = Console.WriteLine;
        Script.RunString(@"[... code ...]");
        Console.ReadLine();
    }
}
```
While I'm at it: Thank you for putting this much effort into MoonSharp and providing it to everyone for free on GitHub. I am a huge fan of the project and using it in various different projects.

**Comment by xanathar** [comment]
Hi.
There two issues here.
The one with the parsing is clearly a MoonSharp bug, thanks for reporting! :) I'll dig into it asap.

The second one (x, x = something() with different values used) is declared as "undefined behavior" in Lua itself (I have asked Roberto Ierusalimschy about that on the Lua mailing list some time ago) and so it's perfectly legal for any Lua interpreter to return the first, the second or even a random value as the result of that call (just as if you call x(i++, i++) in C).

**Comment by xanathar** [comment]
Found on the lua-users wiki:

http://lua-users.org/wiki/AssignmentTutorial

"The order in which multiple assignments are performed is not defined. This means you shouldn't assume the assignments are made from left to right. If the same variable or table reference occurs twice in the assignment list the results may surprise you. [...] Lua does assignments from right-to-left, e.g. [...]. However we shouldn't depend on this being consistent in future versions of Lua. You should use separate assignment statements if the order of assignment is important to you."

**Comment by 7BiTpsycho** [comment]
Okay great! Yep you are right, I probably should have a looked that one up :)
Thank you for taking your time!
