### ISSUE TITLE
__newindex not supported?

### ISSUE THREAD

**Issue by pkuvegeta** [xanathar/moonsharp#133]
local aClass = {}
setmetatable(aClass, {__newindex = function() end, __index = function() end })

local p = {a = 1, b = 2}
for _, v in pairs(p) do
  aClass[_] = v
end

This program break in Moonsharp
It throws exception for attempting to call Tuple (next, table, "a") at the for loop line in the second iteration.

**Comment by xanathar** [comment]
Bad bug.
Checking into it. It's not that __newindex is unsupported or anything.. for some reasons the internal stack gets trashed.

**Comment by xanathar** [comment]
Fixed on master branch.
