### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Executioner1337** [xanathar/moonsharp#139]
I seem to have encountered a memory leak with `script.DoString()`. 
[Posted originally on StackOverflow](http://stackoverflow.com/questions/37828813/why-is-moonsharp-dostring-leaking-memory), each `DoString` call seems to make an instance of a `Script` and it keeps in memory during the runtime. [Here's the overall memory consumption per type](http://i.imgur.com/Rw0sjTV.png), and [here are the objects referred from Script instances](http://i.imgur.com/l42OlUj.png). This certainly an issue since at ~1500 calls per second made the memory usage of the program 200 megabytes in a single minute. Meanwhile with 60 cycles per seconds would reach an `OutOfMemoryException` (between 1.4GB and 2GB) in a much longer time, for a video game that would be released this would be a huge problem. Right now the script is only called once a cycle, during development this will be increased. Visual Studio's own diagnostic tools also show that GCs are ran multiple times a second, yet they do now seem to reduce memory usage.

Any fixes or solutions for this issue? I also tried to post on the forums but the topic wouldn't appear.

**Comment by xanathar** [comment]
Answered on StackOverflow : http://stackoverflow.com/questions/37828813/why-is-moonsharp-dostring-leaking-memory

**Comment by davidm** [comment]
Frequent compilation (load function) might not be best practice, but this does appear to be a bug in MoonSharp compared standard Lua.  Here's a test case:

```
for i=1,100000 do load("x=1") end
collectgarbage()
```

That appends 100000 MoonSharp.Interpreter.DebuggingSourceCode objects to MoonSharp.Interpreter.Script.m_Sources.
Many MoonSharp.Interpreter.Execution.VM.Instruction objects are also appended to MoonSharp.Interpreter.Script.m_ByteCode.Code.
The collectgarbage() call does not clean up here.
