### ISSUE TITLE
Yield and resume

### ISSUE THREAD

**Issue by Fraysa** [xanathar/moonsharp#141]
I have a method that sends a message to the user and then requires user's input until it proceeds.

```
m_script.Globals["send"] = new Action<string>(Send);

private void Send(string text)
{
    Console.WriteLine(text);

    // TODO: halt execution of script?
}
```

Now, I want to be able to display the message, and once I press on any key in the console - resume the script's exceution. Until then, I want to halt the execution.

How can it be achieved? I've tried messing with coroutines but can't figure it out.

**Comment by xanathar** [comment]
Duplicate of #141.
