### ISSUE TITLE
.NETStandard support

### ISSUE THREAD

**Issue by galich** [xanathar/moonsharp#143]
It would be great to have [.NET Standard](https://docs.microsoft.com/en-us/dotnet/articles/standard/library) support out of the box

**Comment by xanathar** [comment]
It's being worked on, but with low priority, sorry.

**Comment by xivk** [comment]
@xanathar Anything I could do to help speed things up?

I'm working in a dependency to moonsharp but I also have to support .NET Standard.

**Comment by xanathar** [comment]
MoonSharp 2.0.0.0 already should already support .NET standard (1.6+).
Let me know if there are any issues.
