### ISSUE TITLE
Performance of table insertion

### ISSUE THREAD

**Issue by nshibano** [xanathar/moonsharp#144]
First of all, I would like to thank you for creating this project.

It seems that the performance of table insertion is slower than intended. Looking at data structure of current implementation of table of MoonSharp, I think it was intended to be O(1) for one insertion. But current master branch is O(N) where N is length of the table.

And found that disabling MoonSharp.Interpreter.Table.CollectDeadKey makes table insertion much faster. This is because CollectDeadKey scans entire table when called.

I have measured execution time of following chunk for n=100, 200 ... 5000.

```
t = {}
for i = 1, n do
	t[i] = true
end
```

Figure below is the comparison of before/after disabling CollectDeadKey.

![table bench2](https://cloud.githubusercontent.com/assets/16814225/17087322/499d651e-5242-11e6-83f4-4f42db8b29ed.png)

The modification I made was commenting out one line from Table.cs. Please see following diff.

https://github.com/nshibano/moonsharp/commit/e7f1690704f3f2645397fd172db41cc70a74b853#diff-94640c765669553d9cc7f0d6b64717e9

I have uploaded entire test bench as fork repository.

https://github.com/nshibano/moonsharp/tree/table-insertion-bench

I am not sure about when/how frequent to call CollectDeadKey. So I couldn't find right way to modify Table.cs.

**Comment by xanathar** [comment]
Fixed in upcoming 1.7.0.0.

Many thanks for this!!
