### ISSUE TITLE
SyntaxErrorException On valid lua lua syntax

### ISSUE THREAD

**Issue by andreluis034** [xanathar/moonsharp#147]
The following code creates a SyntaxErrorException, even though it's valid lua syntax:
`
foo = .5
`
which is equivalent to the working MoonSharp version
`
foo = 0.5
`
The exception is also thrown in conditionals for example:
`
if foo <= .5 then
end
`
Pretty minor bug, but not sure if it affects anything more important stuff.

**Comment by xanathar** [comment]
Fixed in 1.7.
