### ISSUE TITLE
Registering certain types breaks all types registered afterwards

### ISSUE THREAD

**Issue by markonius** [xanathar/moonsharp#153]
Hi!
https://groups.google.com/forum/#!topic/moonsharp/lL8wW7Vpeo4 - related to this issue.

Basically, when I loop through all types in the "System" namespace and register them, all subsequent types that I register don't work as intended. If I try to access any field/property/method of said types I just get some error along the lines of "Can't find field [whatever] in \<System.Object\>".
If I register stuff from System after everything else, then all my types work, but almost everything from System doesn't.

I've done some more digging and noticed that everything breaks after I register System.Attribute.
It might have something to do with the fact that System.Attribute contains a bunch of method that use System.Reflection.

Any ideas?

**Comment by xanathar** [comment]
Mmmh do you have a working snippet or something like that ?

I tried registering System.Attribute and nothing weird happened... everything seems ok. Tried both in .NET and in Unity.

**Comment by markonius** [comment]
http://pastebin.com/jbMEcevH
These are the namespaces I'm trying to register:
public static string[] _sNamespaces = new string[]
		{
			null,
			"UnityEngine",
			"UnityEngine.UI",
			"System.Collections",
//			"System.Collections.Generic",
			"System.IO",
//			"System.Linq",
			"MoonSharp.Interpreter",
			"LuaConsole",
			"System.Xml",
			//"System.Reflection",
			//"System"
		};

If I uncomment any of the commented ones, all types in the subsequent namespaces throw the aforrmentioned error.

**Comment by xanathar** [comment]
I've tried both

```
    public class MyClass
    {
        public string MyMethod()
        {
            return DateTime.Now.ToString("u");
        }
    }

	// Use this for initialization
	void Start () 
    {
        UserData.RegisterType<MyClass>();
        UserData.RegisterType<System.Attribute>();

        Script S = new Script();
        S.Options.DebugPrint = s => Debug.Log(s);

        S.Globals["obj"] = new MyClass();

        S.DoString("print (obj.myMethod());");

        Debug.Log("CUSTOM TEST 1 - DONE");
	}
```

and


```
    public class MyClass
    {
        public string MyMethod()
        {
            return DateTime.Now.ToString("u");
        }
    }

	// Use this for initialization
	void Start () 
    {
        UserData.RegisterType<System.Attribute>();
        UserData.RegisterType<MyClass>();

        Script S = new Script();
        S.Options.DebugPrint = s => Debug.Log(s);

        S.Globals["obj"] = new MyClass();

        S.DoString("print (obj.myMethod());");

        Debug.Log("CUSTOM TEST 1 - DONE");
	}
```

No problems whatsoever in both cases..

**Comment by xanathar** [comment]
Same goes for

```
    public class MyClass
    {
        public string MyMethod()
        {
            return DateTime.Now.ToString("u");
        }
    }

    void RegisterNamespace(string ns)
    {
        string @namespace = "System";

        var q = Assembly.GetExecutingAssembly().GetTypes().Where(t => t.IsClass && t.Namespace == @namespace).ToList();

        q.ForEach(t => UserData.RegisterType(t));
    }

	// Use this for initialization
	void Start () 
    {
        RegisterNamespace("System");


        UserData.RegisterType<MyClass>();


        Script S = new Script();
        S.Options.DebugPrint = s => Debug.Log(s);

        S.Globals["obj"] = new MyClass();

        S.DoString("print (obj.myMethod());");

        Debug.Log("CUSTOM TEST 1 - DONE");
	}
```

... please provide code.
