### ISSUE TITLE
Cannot convert a table to a clr type System.Int32

### ISSUE THREAD

**Issue by Fraysa** [xanathar/moonsharp#154]
My lua script has a function that returns a table of values of byte type.

```
function getSkinStyles(validSkins)
	local currentSkin = getSkin();
	if validSkins == nil then
		validSkins = getAllSkins();
	end
	local styles = {};
	for i = 1, #validSkins do
		local skinId = validSkins[i];
		if skinId ~= currentSkin then
			append(styles, skinId);
		end
	end
	return styles;
end
```

**Note that getAllSkins is a method in my C# application which returns a List<byte> object that contains values.**

I have a method in my C# application that takes a List<byte> as an argument which i'm trying to call from my script.

```
public void SetStyle(List<byte> skins)
```

However, when I'm calling the following:

```
setStyle(getSkinStyles());
```

The compiler throws an exception that it can't call setStyle because the argument is not a List<byte> but a table. How can I convert the table to a List<byte>?

**Comment by Fraysa** [comment]
I got past this by taking DynValue as an argument and then iterating over the values of the DynValue's Table property.

**Comment by xanathar** [comment]
Ok you've solved it.. but in any case there is a default conversion from tables to list, it's odd that it didn't work. Maybe you disabled the default conversions by registering List<byte> ?
