### ISSUE TITLE
when dump UserData to text file, we should  ignore member has ObsoleteAttribute

### ISSUE THREAD

**Issue by issingle** [xanathar/moonsharp#157]

**Comment by xanathar** [comment]
You mean in hardwiring ? Obsolete is not considered neither in userdata mapping not in hardwiring intentionally - after all you *can* call that method from C# so you'd expect to be able to call it from Lua if exposed in a script. Use a proxy type in case you want to hide those members (BTW, exposing objects you don't control to scripts is *not* recommended).

**Comment by issingle** [comment]
But ...make  proxy type is a big work if we want to dev a unity3d app.

**Comment by xanathar** [comment]
Get the descriptor and remove the members with RemoveMember methods ?
