### ISSUE TITLE
stringTypeDynValue.ToString() is surrounded by quotes

### ISSUE THREAD

**Issue by rmcrackan** [xanathar/moonsharp#159]
In MoonSharp 1.8.0.0, these unit tests pass for me. The final one should not:

            DynValue retCiao = Script.RunString("return 'ciao'");
            Assert.AreEqual(DataType.String, retCiao.Type);
            // expected
            Assert.AreEqual("ciao", retCiao.String);
            // unexpected
            Assert.AreEqual("\"ciao\"", retCiao.ToString());

**Comment by xanathar** [comment]
It's by design - ToString is used for debugging purposes. Use the String property to get the string value.
