### ISSUE TITLE
Lua Lanes?

### ISSUE THREAD

**Issue by binjobrush** [xanathar/moonsharp#164]
Hi,

I was wondering if you will be implementing the Lua Lanes library into moonsharp or have plans to?  

If not, how would you recommend starting if I was to implement it myself?

Thanks,
Jason

**Comment by xanathar** [comment]
Sorry I don't know Lua lanes so I have no idea on how you could implement it; not sure even if feasible as implementation and threading differ heavily from standard lua.

Good luck and sorry for not being of help (and the late answer).
