### ISSUE TITLE
Is it possible dispose script object?

### ISSUE THREAD

**Issue by netpyoung** [xanathar/moonsharp#176]
for eaxmple
when i create coroutine from script.
can i dispose script object and corutine object?

```cs
var script =  new Script(CoreModules.Preset_Complete);
var coroutine = script.CreateCoroutine (co_main);
var enumerator coroutine.Coroutine.AsEnumerable<IEnumerator> ();
```

**Comment by xanathar** [comment]
They don't use any non-native resource.. so it doesn't make sense to call Dispose on them.
Why are you asking ?
