### ISSUE TITLE
unity3d how to change position of object 

### ISSUE THREAD

**Issue by friuns2** [xanathar/moonsharp#195]
hello i'm looking for interpreters for my game, choosing between jurassic and moonsharp. but can't get moonsharp work with unity..

this code not work

       UserData.RegistrationPolicy = InteropRegistrationPolicy.Automatic;
        UserData.RegisterAssembly();
        UserData.RegisterType<Vector3>();
        UserData.RegisterType<Transform>();
        UserData.RegisterType<Player>();
        script.Globals["Vector3"] = typeof(Vector3);
        script.Globals["self"] = this;
        script.DoString("self.transform.position= Vector3.new(1,1,1)");

please help

**Comment by CerosWare** [comment]
You could load your script in a DynValue, then call its Function object.

`UserData.RegistrationPolicy = InteropRegistrationPolicy.Automatic;`
`UserData.RegisterAssembly();`
`UserData.RegisterType<Vector3>();`
`UserData.RegisterType<Transform>();`

`s.Globals["t"] = this.transform;`
`s.Globals["v"] = new Vector3(1,1,1);`
`f = s.LoadString(@"`
               ` t.position = v `
        `");`
`f.Function.Call();`
