### ISSUE TITLE
Module not found  - Script run time error when using required in Lua script

### ISSUE THREAD

**Issue by sureshaddaguduru** [xanathar/moonsharp#48]
Hi,

Please let me know how to resolve this error. I am new to Lua.

Thank you.

Regards,
Suresh

**Comment by xanathar** [comment]
Hi,
what are you trying to attempt exactly ? 
Can you paste some Lua and C# code here to repro the issue ?

**Comment by sureshaddaguduru** [comment]
Hi Marco,

I am trying to run a lua script from .net using moonsharp. That luascript
internally using luasocket mime\core.dll and socket\core.dll files.

The lua script is working fine when I run it in Lua. But when I run the
script from .net application, it is throwing an exception.

Lua Code(Test.lua):

local socket = require("socket.core")
module('socket')


.Net Code:

DynValue res = Script.RunFile("Test.lua");

Exception:

module socket.core not found. (All the dlls are available for the script
and .net environment.)

Please help me how to access .dll reside in the lua script using C#.

Thank you very much.

Regards,
Suresh



On Fri, Jan 9, 2015 at 12:31 PM, Marco Mastropaolo <notifications@github.com
> wrote:

> Hi,
> what are you trying to attempt exactly ?
> Can you paste some Lua and C# code here to repro the issue ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xanathar/moonsharp/issues/48#issuecomment-69368161>.
>



-- 
Regards,
Suresh
703-209-8728.

**Comment by xanathar** [comment]
Ok. Loading of DLLs is not supported, or other C modules, as this is a reimplementation of the language and uses a different API, sorry.

You can use require to load modules implemented in lua but not those implemented in C.
