### ISSUE TITLE
Exception on running scimark.lua

### ISSUE THREAD

**Issue by jagt** [xanathar/moonsharp#52]
[`scimark.lua`](http://luajit.org/download/scimark.lua) is a commonly used script commonly used for naively measuring Lua implementation performance. When I tried to run it under moonsharp it errors out very early.

```
MoonSharp REPL 0.8.5.0 [clr-2]
Copyright (C) 2014 Marco Mastropaolo
http://www.moonsharp.org
Based on Lua 5.1 - 5.3, Copyright (C) 1994-2014 Lua.org
License: https://raw.githubusercontent.com/xanathar/moonsharp/master/LICENSE


Unhandled Exception:  System.IndexOutOfRangeException:
    MoonSharp.Interpreter.Execution.VM.Processor.AssignLocal(SymbolRef symref, DynValue value)  c:\git\moonsharp\src\MoonSharp.Interpreter\Execution\VM\Processor\Processor_InstructionLoop.cs: line no 334
    MoonSharp.Interpreter.Execution.VM.Processor.Processing_Loop(Int32 instructionPtr) c:\git\moonsharp\src\MoonSharp.Interpreter\Execution\VM\Processor\Processor_InstructionLoop.cs:line no 197
   MoonSharp.Interpreter.Execution.VM.Processor.Call(DynValue function, DynValue[] args) c:\git\moonsharp\src\MoonSharp.Interpreter\Execution\VM\Processor\Processor.cs:line no 69
   MoonSharp.Program.Main(String[] args) c:\git\moonsharp\src\MoonSharp\Program.cs:line no 37
```

I've also tried this on `master` and it's the same error. I suspect it's something wrong with the scoping.

Thanks.

**Comment by jagt** [comment]
I've managed to reproduce this error with this simpler case:

```lua
local foo, bar

function bar()
    print('bar')
    function foo()
        print('foo')
    end
end

bar()
foo()
```

**Comment by xanathar** [comment]
Sure I'll will check!
Today I'm still busy with the global game jam here, but I think I can debug and hopefully fix this on Tuesday.

Thanks for the very detailed report!

**Comment by jagt** [comment]
No problem :) Good luck with the game jam!

**Comment by xanathar** [comment]
Checking it right now.. thanks for the report, the bug is very nasty.. on the level that makes one wonder how could the rest work :)

Your analysis is mostly correct, the scope stack leaks an entry and so bar is effectively out of scope.. but to makes things more funny it also jumps at the wrong instruction, thus calling bar() twice (one time when it's out of scope).

Don't ask how scripts a lot more complex than this can run with no problems, no idea :P will fix ASAP!

**Comment by xanathar** [comment]
Fixed in master branch.

**Comment by jagt** [comment]
Seems removing the `(bc.GetLastInstruction().OpCode != OpCode.Ret)` check fixes this problem?

**Comment by xanathar** [comment]
Yes, that was the fix :) 

(Stupid optimization).
