### ISSUE TITLE
LuaParser is not complete?

### ISSUE THREAD

**Issue by luzexi** [xanathar/moonsharp#54]
I want to use lua interpreter in unity3d project ,
so I put the MoonSharp.Interpreter folder and Antlr4.Runtime.net20.dll in my unity3d project , it tell me this:

Assets/App/Scripts/submodule/Unity3DLua/MoonSharp.Interpreter/Tree/Expressions/DynamicExpression.cs(14,56): error CS0426: The nested type `DynamicexpContext' does not exist in the type `MoonSharp.Interpreter.Grammar.LuaParser'

I check the class LuaParser , but it is nothing in it.
Is it my problem?
How can I do?

**Comment by xanathar** [comment]
Hi.
To use the solution in Unity, just reference the DLLs.
To build the DLL from sources, you need to follow the guide at the antlr4cs project: https://github.com/tunnelvisionlabs/antlr4cs

LuaParser.cs is generated automagically at compile time after ANTLR4 is installed in Visual Studio.

If you want to try referencing the generated files directly, I've zipped them and put them on dropbox:  https://www.dropbox.com/s/g13g7kb0lm1qujk/Generated_ANTLR_Parser.zip?dl=0

Let me know if they work for you.
