### ISSUE TITLE
Redirecting print and io

### ISSUE THREAD

**Issue by jernejk** [xanathar/moonsharp#56]
Hi.

I want to build an app for fast prototyping simple algorithms for Windows and Windows Phone.
How can I get output of print and io without writing entire proxy class?

I already have couple of scripts written in Lua and they are working with LuaInterface and I need consistent print/io formatting with minimum amount of work if possible.

Thanks,
Jernej

**Comment by xanathar** [comment]
Hi,
print is easy .. check this : http://www.moonsharp.org/recipes.html 

For io, I guess you can use the standard Lua way of changing stdin, but I think I didn't leave C# access to that. I will add support for it in some way.

**Comment by jernejk** [comment]
Thank you, this will help me a lot. :)
I don't know how I missed this one with print.

If you could give access for changing stdin, that would be great. :)

**Comment by xanathar** [comment]
Done . Will be released in the next few days with the 0.9.0 bunch of stuff.
