### ISSUE TITLE
RunFile and missing module((...), arguments)

### ISSUE THREAD

**Issue by ghost** [xanathar/moonsharp#57]
A little context first.  I'm loading lua files I have no control over and so can't simply remove the arguments in advance.  So, given a file like the following:

```lua
module((...), this_doesnt_exist)
something = {
}
```

I try 
```c#
var x = Script.RunFile("test.lua");
```

and receive "attempt to call a nil value near 'module((...),this_doesnt_exist)'"

So, I thought I could just grab the name of the missing function from the exception message and programmatically build the required function, inject this into the context and rerun the file.  So I ended up with this little mess:

```c#
var lua = new Script();
var context = new Table(lua);
DynValue y = new DynValue();

while (y.IsNil())
{
    var x = lua.LoadFile("test.lua", context);

    try
    {
        lua.Call(x);
    }
    catch (ScriptRuntimeException exception)
    {
        string missing = exception.Message.Substring(exception.Message.IndexOf(",") + 1);
        missing = missing.Substring(0, missing.Length - 2);

        lua.LoadFunction("function (args) end", context, missing);
    }

    y = lua.Globals.Get("something");
}
```

But this just loops forever.  I'm not entirely sure this is even the best approach.  Any advice or pointers would be gratefully received.

**Comment by jagt** [comment]
[`module` function is deprecated in Lua 5.2](http://www.lua.org/manual/5.2/manual.html#8.2) and seems MoonSharp didn't implement `module` function. I'm suppose you'll have to make some change to the code or implement `module` on your own.

**Comment by ErrolErrolson** [comment]
Thanks jagt, I just assumed it was because "this_doesnt_exist" didn't exist, not because module didn't!

I'll take a look at how the other base LUA methods are implemented like ```require``` and have a go at implementing ```module```

**Comment by MaxxWyndham** [comment]
Umm, decided to consolidate my github accounts.  That ghost is me.  Sorry!
