### ISSUE TITLE
ModulePaths OutOfRange / Overflow Bug

### ISSUE THREAD

**Issue by atom0s** [xanathar/moonsharp#94]
There is a bug with the ModulePaths property where you can cause an application to crash due to an overflow or an out of range exception. If you set the path to the same file that is currently being executed the application will crash. 

For example:
```csharp
    var basePath = AppDomain.CurrentDomain.BaseDirectory;
    var scriptPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "scripts", "test");
    ((ScriptLoaderBase)script.Options.ScriptLoader).ModulePaths = new[]
            {
                Path.Combine(basePath, "scripts", "test", "test.lua"),
            };
    var obj = script.LoadFile(Path.Combine(scriptPath, "test.lua"));
    obj.Function.Call();
```
This application will crash on the function call due to the inclusion issue.

**Comment by xanathar** [comment]
Thanks, will look into it.

**Comment by xanathar** [comment]
Sorry.. can't repro :(
