### ISSUE TITLE
IronPython compatibilty

### ISSUE THREAD

**Issue by dretax** [xanathar/moonsharp#96]
There seem to be compatibility issues with IronPython.

Running this code: http://pastie.org/private/2mdpllqawz8tgmgrb1xw5a

Getting this error: http://pastie.org/private/slhvzjwhc3jm7ccdvujh2a

Running Jint or any other C# modules in my project doesn't cause issue with MoonSharp. It loads fine, and works. Once I enable loading IronPython, MoonSharp stops loading at:  script = new MoonSharp.Interpreter.Script();

(Without try catch It does the same)

**Comment by xanathar** [comment]
Good catch - I'll fix it asap.

**Comment by dretax** [comment]
Cheers

**Comment by xanathar** [comment]
No success in reproing this.
I prepared a build with a handy "try..catch" which should block the deadly exception.. if you can try it..

https://www.dropbox.com/s/9vn8gwfmk9yc2t4/MoonSharp_0.9.7.1.zip?dl=0

**Comment by dretax** [comment]
Bug seems to be fixed, all the stuffs are in the globals as they should be. I'm gonna do some futher testing, but the engine seems to work!

**Comment by xanathar** [comment]
Fantastic thanks.
If you find further bugs, open another issue then! :+1:
